--- 
- !ruby/object:OpenMirror::Event 
  actions: 
  - !ruby/object:OpenMirror::Action::Execute 
    command: git commit -a -m "commit via les lapins"
  matches: 
  - !ruby/object:OpenMirror::Event::Match 
    field: :action
    value: "05"
  name: Git commit projet xyz
- !ruby/object:OpenMirror::Event 
  actions: 
  - !ruby/object:OpenMirror::Action::Execute 
    command: |
      tar cvjf ./`date +"%d-%m-%Y_%Hh%Mm"`.tar ./TBachelor

  matches: 
  - !ruby/object:OpenMirror::Event::Match 
    field: :action
    value: "02"
  name: Backup projet xyz
- !ruby/object:OpenMirror::Event 
  actions: 
  - !ruby/object:OpenMirror::Action::HTTP_URL 
    data: ""
    headers: {}

    method: :GET
    params: {}

    url: !ruby/object:URI::HTTP 
      fragment: 
      host: 10.192.45.2
      opaque: 
      password: 
      path: /badger/@(id)
      port: 80
      query: 
      registry: 
      scheme: http
      user: 
  matches: 
  - !ruby/object:OpenMirror::Event::Match 
    field: :action
    value: "01"
  name: Badger sur projet xyz
